name: ai_prompt_organizer
description: For organizing AI prompts

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  realm: ^0.5.0+beta
  file_picker: ^5.2.1
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  # the material Icons class.
  uses-material-design: true
